# Generated by Django 5.2.6 on 2025-09-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_admin_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('mairie', 'Mairie'), ('user', 'Utilisateur')], default='user', max_length=20),
        ),
    ]
