# Generated by Django 5.2.6 on 2025-09-18 22:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_acte', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='actes_pdfs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provinces.province')),
            ],
        ),
    ]
