# Generated by Django 5.2.6 on 2026-03-13 21:24

import actes.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0002_actenaissance_created_by_actenaissance_modified_by'),
        ('provinces', '0002_alter_province_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actenaissance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], db_index=True, default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to=actes.models.acte_pdf_path),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='numero_acte',
            field=models.CharField(db_index=True, help_text="Numéro unique de l'acte de naissance", max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actes_naissance', to='provinces.province'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=actes.models.qr_code_path),
        ),
        migrations.AddIndex(
            model_name='actenaissance',
            index=models.Index(fields=['numero_acte', 'nom'], name='actes_acten_numero__918db5_idx'),
        ),
        migrations.AddIndex(
            model_name='actenaissance',
            index=models.Index(fields=['province', 'date_naissance'], name='actes_acten_provinc_7b650a_idx'),
        ),
    ]
